; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[nano33ble]
platform = nordicnrf52 @ 10.11.0
board = nano33ble
framework = arduino
build_flags = 
lib_deps =  https://github.com/tensorflow/tflite-micro-arduino-examples.git#7948b85
            https://github.com/kosme/arduinoFFT.git#v2.0.4
extra_scripts = pre:scripts/model_check.py
monitor_echo = yes
monitor_filters = send_on_enter

[collectData]
build_flags =   -DCOLLECT_DATA

[collectRest]
build_flags =   -DCOLLECT_REST

[env:nano33ble_SenseRev2]
extends = nano33ble
build_flags =   ${nano33ble.build_flags}
                -DNANO33BLE_SENSE_REV2
lib_deps =  ${nano33ble.lib_deps}
            https://github.com/arduino-libraries/Arduino_BMI270_BMM150#1.2.3

[env:nano33ble_Sense]
extends = nano33ble
build_flags =   ${nano33ble.build_flags}
                -DNANO33BLE_SENSE
lib_deps =  ${nano33ble.lib_deps}
            https://github.com/arduino-libraries/Arduino_LSM9DS1#1.1.1

[env:nano33ble_SenseRev2_CollectData]
extends = env:nano33ble_SenseRev2, collectData
build_flags =   ${env:nano33ble_SenseRev2.build_flags}
                ${collectData.build_flags}

[env:nano33ble_Sense_CollectData]
extends = env:nano33ble_Sense, collectData
build_flags =   ${env:nano33ble_Sense.build_flags}
                ${collectData.build_flags}

[env:nano33ble_SenseRev2_CollectData_Rest]
extends = env:nano33ble_SenseRev2, collectData
build_flags =   ${env:nano33ble_SenseRev2.build_flags}
                ${collectData.build_flags}
                ${collectRest.build_flags}

[env:nano33ble_Sense_CollectData_Rest]
extends = env:nano33ble_Sense, collectData
build_flags =   ${env:nano33ble_Sense.build_flags}
                ${collectData.build_flags}
                ${collectRest.build_flags}
                
